### PR TITLE
Issue #152 - WIP (added initial feature)

### PR DESCRIPTION
**Pull request by jbatte47**

### CODE REVIEW

**Comment by jbatte47** [comment]
@chrislwade, @blaw2422 : I assigned this PR to Justin so he could review the new feature, but you guys feel free to chime in too

**Comment by jbatte47** [comment]
It should also probably be noted that I'll be squashing this down, hence the informal PR format.

**Comment by chrislwade** [comment]
See [`Array#compact`](http://www.ruby-doc.org/core-1.9.3/Array.html#method-i-compact) from Ruby.

**Comment by jbatte47** [comment]
Yeah, per what @chrislwade just found, it probably makes more sense to name it after something other languages already support. We'll call it `Compact`, so the call structure can look like:

``` csharp
var results = set.EmptyIfNull().Compact().Select(item => item.Value);
```

**Comment by jlmorgan** [comment]
Seems legit.

**Comment by chrislwade** [comment]
Ruby doesn't have an equivalent for `EmptyIfNull` as that would require polluting `NilObject` with things `nil` shouldn't be concerned with.

**Pull request merged**
